import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useRef } from 'react'
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/router'

async function createUser(username, password) {
  const response = await fetch('/api/user', {
    method: 'POST',
    body: JSON.stringify({ username, password }),
    headers: {
      'Content-Type': 'application/json',
    },
  })

  const data = await response.json()

  if (!response.ok) {
    throw new Error(data.message || 'Something went wrong!')
  }

  return data
}

export default function Home() {
  const usernameInputRef = useRef()
  const passwordInputRef = useRef()

  const [isLogin, setIsLogin] = useState(true)
  const router = useRouter()

  function switchAuthModeHandler() {
    setIsLogin((prevState) => !prevState)
  }

  async function submitHandler(event) {
    event.preventDefault()

    const enteredUsername = usernameInputRef.current.value
    const enteredPassword = passwordInputRef.current.value

    // optional: Add validation

    if (isLogin) {
      const result = await signIn('credentials', {
        redirect: false,
        username: enteredUsername,
        password: enteredPassword,
      })

      if (!result.error) {
        // set some auth state
        router.replace('/authenticated')
      }
    } else {
      try {
        const result = await createUser(enteredUsername, enteredPassword)
        console.log(result)
      } catch (error) {
        console.log(error)
      }
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href='/authenticated'>Authenticated</a>
        </h1>
        <form onSubmit={submitHandler}>
          <div className={styles.control}>
            <label htmlFor='email'>Your Email</label>
            <input type='email' id='email' required ref={usernameInputRef} />
          </div>
          <div className={styles.control}>
            <label htmlFor='password'>Your Password</label>
            <input
              type='password'
              id='password'
              required
              ref={passwordInputRef}
            />
          </div>
          <div className={styles.actions}>
            <button>{isLogin ? 'Login' : 'Create Account'}</button>
            <button
              type='button'
              className={styles.toggle}
              onClick={switchAuthModeHandler}>
              {isLogin ? 'Create new account' : 'Login with existing account'}
            </button>
          </div>
        </form>
      </main>
    </div>
  )
}
